---
# Source: demoapp/charts/lambda/templates/lambda.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: prod-lambda
  namespace: ack-lambda
  annotations:
    services.k8s.aws/region: us-east-2
spec:
  name: prod-lambda
  packageType: Image
  code:
    imageURI: 884185907314.dkr.ecr.us-east-2.amazonaws.com/prod/lambda:93d5026f
  role: arn:aws:iam::884185907314:role/prod-lambda-execution-role
  description: function created by ACK lambda-controller
  timeout: 30
  memorySize: 256
  environment:
    variables:
      S3_BUCKET_NAME: prod-app-output-files-884185907314
      DYNAMODB_TABLE_NAME: prod-pdf-files-per-user-descriptors
